component_depth: 1
languages:
  - python
  - go
  - typescript
  - javascript
  - script
exclude:
  - /cc_library/example-scripts-js-scc/.*
  - /cc_library/py-scc/src/sciler/scripts/.*
  - /front-end/karma.conf.js