# https://docs.travis-ci.com/user/customizing-the-build
matrix:
  include:
      # https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages
    - language: python
      python: 3.7
      install:
        - pip install -r cc-library/requirements.txt
      before_script:
        cd cc-library/test
      script:
        - python -m unittest discover

      # https://medium.com/faun/configuring-travis-ci-for-angular-application-34afee1715f
    - language: node_js
#      dist: trusty
#      sudo: true
      node_js:
        - "12.13.1" 
      before_script:
        - cd front-end/
        - npm install -g @angular/cli
        - npm update
      cache:
        directories:
          - node_modules
      script:
        - ng lint
        - ng test # npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
        - ng e2e
#        - xvfb-run npm run e2e
      addons:
        chrome: stable
#        apt:
#          sources:
#            - google-chrome
#          packages:
#            - google-chrome-stable

    - language: go
      before_install:
        - go get -u golang.org/x/lint/golint
        - go get -u github.com/stretchr/testify/assert
      script:
        - go build
        - ./back-end/.travis.gofmt.sh
        - test -z "`golint ./...`"
        - go test back-end/test
