# https://docs.travis-ci.com/user/customizing-the-build
matrix:
  include:
      # https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages
    - language: python
      python: 3.7
      install:
        - pip install -r cc_library/requirements.txt
      script:
        - flake8 cc_library
        - python -m unittest discover

      # https://medium.com/faun/configuring-travis-ci-for-angular-application-34afee1715f
    - language: node_js
      node_js: 12.13.1
      services:
        - xvfb
      dist: xenial
      before_script:
        - cd front-end/
        - npm install -g @angular/cli
        - npm update
        - export DISPLAY=:99.0
      cache:
        directories:
          - node_modules
      script:
        - ng lint
        - ng test --watch=false
#        - ng e2e
      addons:
        chrome: stable

    - language: go
      go: 1.13.4
      go_import_path: github.com/IssaHanou/BEP_1920_Q2/back-end
      before_install:
        - export GOPATH=$TRAVIS_BUILD_DIR/back-end
        - ls
        - cd back-end/src/sciler
        - ls
        - go get github.com/stretchr/testify/assert
        - mkdir -p $GOPATH/src/golang.org/x/
        - cd ../golang.org/x/
        - git clone https://github.com/golang/tools.git
#        - go get -u golang.org/x/lint/golint
        - cd ../../sciler
      script:
        - ls
        - cd ../..
        - ls
        - golint -set_exit_status sciler/...
        - go test -v sciler/...
        - go build sciler
