# https://docs.travis-ci.com/user/customizing-the-build
matrix:
  include:
      # https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages
    - language: python
      python: 3.7
      install:
        - pip install -r cc-library/requirements.txt
      before_script:
        cd cc-library/test
      script:
        - python -m unittest discover

      # https://medium.com/faun/configuring-travis-ci-for-angular-application-34afee1715f
    - language: node_js
      before_script:
        - npm install -g @angular/cli
      script:
        - ng build --prod
        - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
      cache:
        directories:
          - node_modules
          - front-end/node-modules
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable

    - language: go
      before_install:
        - go get -u golang.org/x/lint/golint
        - go get -u github.com/stretchr/testify/assert
      script:
        - go build
        - ./back-end/.travis.gofmt.sh
        - test -z "`golint ./...`"
        - go test back-end/test
